// examples/react-example.jsx
/**
 * React 예제 (React 18+)
 * 
 * 설치:
 * npm install ga-like-recommend-sdk
 * 
 * 또는 프로젝트에 직접 복사 후:
 * import RecommendSDK from '../dist/browser/recommend-sdk.mjs'
 */

import React, { useEffect, useState } from 'react';
import RecommendSDK from 'ga-like-recommend-sdk';

// SDK 초기화 (앱 최상단에서 1회만)
// App.js 또는 _app.js 에서 실행
function initSDK() {
  RecommendSDK.init({
    env: 'production', // 필수
    domainId: 'your-domain-id', // 선택
    // 나머지는 기본값 사용 (autoRouteTracking: true 등)
  });
}

// 상품 페이지 컴포넌트
function ProductPage({ productId }) {
  const [product, setProduct] = useState(null);
  const [selectedOptions, setSelectedOptions] = useState([]);

  useEffect(() => {
    // 페이지 뷰는 autoPageView: true 이면 자동으로 전송됨
    // 추가 데이터를 보내고 싶다면:
    RecommendSDK.trackEvent('view_item', {
      sku: productId,
      category: 'electronics',
    });
  }, [productId]);

  useEffect(() => {
    // demo product
    setProduct({
      sku: productId,
      name: '노트북',
      price: 1500000,
    });
  }, [productId]);

  const onSelectOption = (name, value) => {
    const next = [...selectedOptions, { name, value }];
    setSelectedOptions(next);

    // 5) sku 같은 option payload 추가 예제 (선택할 때마다 이벤트 + 누적 옵션)
    RecommendSDK.trackEvent('select_option', {
      sku: productId,
      optionName: name,
      optionValue: value,
      selectedOptions: next,
    });
  };

  const handleAddToCart = () => {
    // 즉시 전송 (immediateEventTypes에 등록됨)
    RecommendSDK.trackEvent('add_to_cart', {
      sku: product.sku,
      name: product.name,
      price: product.price,
      quantity: 1,
      options: selectedOptions,
    });
  };

  const handlePurchase = () => {
    // 즉시 전송
    RecommendSDK.trackEvent('purchase', {
      orderId: `ORD-${Date.now()}`,
      amount: product.price,
      paymentMethod: 'unknown',
      items: [{ sku: product.sku, quantity: 1, options: selectedOptions }],
    });
  };

  // 4) 구매시, 카드 구입 이벤트 예제
  const handleCardPurchase = () => {
    RecommendSDK.trackEvent('purchase', {
      orderId: `ORD-${Date.now()}`,
      amount: product.price,
      paymentMethod: 'card',
      items: [{ sku: product.sku, quantity: 1, options: selectedOptions }],
      card: { issuer: 'demo', installmentMonths: 0 },
    });
  };

  return (
    <div>
      <h1>{product?.name}</h1>
      <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
        <button onClick={() => onSelectOption('color', 'black')}>색상: black</button>
        <button onClick={() => onSelectOption('color', 'silver')}>색상: silver</button>
        <button onClick={() => onSelectOption('size', 'M')}>사이즈: M</button>
      </div>
      <button onClick={handleAddToCart}>장바구니 담기</button>
      <button onClick={handlePurchase}>구매하기</button>
      <button onClick={handleCardPurchase}>카드 결제</button>
    </div>
  );
}

// 추천 받기 예제
function RecommendationWidget() {
  const [recommendations, setRecommendations] = useState([]);

  useEffect(() => {
    async function fetchRecommendations() {
      const result = await RecommendSDK.recommend({
        context: {
          category: 'electronics',
          page: 'home',
        }
      });
      
      if (result && result.items) {
        setRecommendations(result.items);
      }
    }

    fetchRecommendations();
  }, []);

  return (
    <div>
      <h2>추천 상품</h2>
      {recommendations.map(item => (
        <div key={item.sku}>{item.name}</div>
      ))}
    </div>
  );
}

// App 컴포넌트
function App() {
  const [userId, setUserId] = useState(null);
  const canLogout = !!userId;

  useEffect(() => {
    initSDK();
  }, []);

  // 2) 로그인 유저 인증관련 (identify)
  const login = () => {
    const id = 'user_' + Math.random().toString(36).slice(2, 8);
    setUserId(id);
    RecommendSDK.identify({ userId: id });
  };

  // 3) 로그아웃 로그 인증관련 (logout)
  const logout = () => {
    RecommendSDK.logout();
    setUserId(null);
  };

  return (
    <div>
      <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
        <button onClick={login}>로그인</button>
        <button onClick={logout} disabled={!canLogout}>로그아웃</button>
        <span>userId: {userId || '(guest)'}</span>
      </div>
      <ProductPage productId="LAPTOP-001" />
      <RecommendationWidget />
    </div>
  );
}

export default App;

// ============================================
// React Router v6 통합 (선택사항)
// ============================================

import { useLocation } from 'react-router-dom';

function RouteTracker() {
  const location = useLocation();

  useEffect(() => {
    // autoRouteTracking: true 이면 자동으로 감지하지만,
    // React Router의 location 변경을 수동으로 추적하고 싶다면:
    RecommendSDK.trackPageView(window.location.href, {
      path: location.pathname,
      search: location.search,
    }, { immediate: true });
  }, [location]);

  return null;
}

// _app.js 또는 App.js에 추가:
// <RouteTracker />

// examples/vue-example.vue
<!--
  Vue 3 예제
  
  설치:
  npm install ga-like-recommend-sdk
  
  또는:
  import RecommendSDK from '../dist/browser/recommend-sdk.mjs'
-->

<template>
  <div>
    <div style="display:flex; gap:8px; align-items:center; margin-bottom: 16px;">
      <button @click="login">로그인</button>
      <button @click="logout" :disabled="!userId">로그아웃</button>
      <span>userId: {{ userId || '(guest)' }}</span>
    </div>
    <h1>{{ product.name }}</h1>
    <p>가격: {{ product.price.toLocaleString() }}원</p>
    <div style="display:flex; gap:8px; margin-bottom: 12px;">
      <button @click="selectOption('color', 'black')">색상: black</button>
      <button @click="selectOption('color', 'silver')">색상: silver</button>
      <button @click="selectOption('size', 'M')">사이즈: M</button>
    </div>
    <button @click="handleAddToCart">장바구니 담기</button>
    <button @click="handlePurchase">구매하기</button>
    <button @click="handleCardPurchase">카드 결제</button>

    <div class="recommendations">
      <h2>추천 상품</h2>
      <div v-for="item in recommendations" :key="item.sku">
        {{ item.name }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue';
import { useRoute } from 'vue-router'; // Vue Router 사용 시
import RecommendSDK from 'ga-like-recommend-sdk';

const product = ref({
  sku: 'LAPTOP-001',
  name: '노트북',
  price: 1500000
});

const recommendations = ref([]);
const selectedOptions = ref([]);

// 2) 로그인 유저 인증관련
const userId = ref(null);
const login = () => {
  userId.value = 'user_' + Math.random().toString(36).slice(2, 8);
  RecommendSDK.identify({ userId: userId.value });
};

// 3) 로그아웃 로그 인증관련
const logout = () => {
  RecommendSDK.logout();
  userId.value = null;
};

// ============================================
// SDK 초기화 (main.js 또는 App.vue에서 1회)
// ============================================
onMounted(() => {
  // 1) 초기화 init
  RecommendSDK.init({ env: 'production', domainId: 'your-domain-id' });

  // 페이지 뷰 추적 (autoPageView: true 이면 자동)
  RecommendSDK.trackEvent('view_item', {
    sku: product.value.sku,
    category: 'electronics',
  });

  // 추천 받기
  fetchRecommendations();
});

// ============================================
// 이벤트 핸들러
// ============================================
const handleAddToCart = () => {
  RecommendSDK.trackEvent('add_to_cart', {
    sku: product.value.sku,
    name: product.value.name,
    price: product.value.price,
    quantity: 1,
    options: selectedOptions.value.slice(),
  });
  alert('장바구니에 추가되었습니다!');
};

const handlePurchase = () => {
  RecommendSDK.trackEvent('purchase', {
    orderId: `ORD-${Date.now()}`,
    amount: product.value.price,
    paymentMethod: 'unknown',
    items: [{ sku: product.value.sku, quantity: 1, options: selectedOptions.value.slice() }],
  });
  alert('구매가 완료되었습니다!');
};

// 4) 구매시, 카드 구입 이벤트 예제
const handleCardPurchase = () => {
  RecommendSDK.trackEvent('purchase', {
    orderId: `ORD-${Date.now()}`,
    amount: product.value.price,
    paymentMethod: 'card',
    items: [{ sku: product.value.sku, quantity: 1, options: selectedOptions.value.slice() }],
    card: { issuer: 'demo', installmentMonths: 0 },
  });
  alert('카드 결제 완료!');
};

// 5) sku 같은 option payload 추가 예제
const selectOption = (name, value) => {
  selectedOptions.value = [...selectedOptions.value, { name, value }];
  RecommendSDK.trackEvent('select_option', {
    sku: product.value.sku,
    optionName: name,
    optionValue: value,
    selectedOptions: selectedOptions.value.slice(),
  });
};

// ============================================
// 추천 받기
// ============================================
const fetchRecommendations = async () => {
  const result = await RecommendSDK.recommend({
    context: {
      category: 'electronics',
      page: 'product',
      sku: product.value.sku,
    }
  });

  if (result && result.items) {
    recommendations.value = result.items;
  }
};

// ============================================
// Vue Router 통합 (선택사항)
// ============================================
const route = useRoute();

watch(() => route.fullPath, (newPath) => {
  // autoRouteTracking: true 이면 자동으로 감지하지만,
  // Vue Router의 route 변경을 수동으로 추적하고 싶다면:
  RecommendSDK.trackPageView(window.location.href, {
    path: route.path,
    query: route.query,
  }, { immediate: true });
});
</script>

<style scoped>
.recommendations {
  margin-top: 30px;
  padding: 20px;
  border: 1px solid #ddd;
}
</style>
